### ISSUE TITLE
[Chapter4] Inconsistent notation of stochastic kernels

### ISSUE THREAD

**Issue by sayaikegawa** [jstac/edtc-code#10]
Hi @jstac ,

In pdf, there are two stochastic kernels such as p_H and p_Q as follows.
<img width="442" alt="Screen Shot 2021-09-10 at 9 58 39 pm" src="https://user-images.githubusercontent.com/44494439/132936810-591a4714-82e4-4834-a8b0-b543a3ae36c0.png">
<img width="497" alt="Screen Shot 2021-09-10 at 9 58 53 pm" src="https://user-images.githubusercontent.com/44494439/132936815-9cff8113-0132-4c41-bbf8-0f11f7a31da4.png">

However, the notations of those kernels are not consistent in code book. For example, p_Q is written as p_Q but p_H is written as p_H and pH as follows. Which notation would you prefer? (The easier way to fix is change p_Q to pQ and p_H to pH. But I can fix in either way. )
<img width="955" alt="Screen Shot 2021-09-10 at 10 07 00 pm" src="https://user-images.githubusercontent.com/44494439/132937014-299301c2-bd8b-44cb-9e2d-c41d89873317.png">
<img width="964" alt="Screen Shot 2021-09-10 at 10 07 50 pm" src="https://user-images.githubusercontent.com/44494439/132937016-e47624b7-4328-4c88-85f2-9be7952f0897.png">

**Comment by jstac** [comment]
Thanks @sayaikegawa :-)

Fixed.
