### ISSUE TITLE
[chapter6] pdf typo

### ISSUE THREAD

**Issue by sayaikegawa** [jstac/edtc-code#14]
Hi @jstac ,

The yellow colored place should be "figure 6.7". 

<img width="964" alt="Screen Shot 2021-09-11 at 9 52 55 am" src="https://user-images.githubusercontent.com/44494439/132955317-a3a9a185-058f-41b8-83d5-2fd816a1af1f.png">

**Comment by jstac** [comment]
Thanks Saya!  Fixed.
