### ISSUE TITLE
PDF typos

### ISSUE THREAD

**Issue by sayaikegawa** [jstac/edtc-code#21]
Hi @jstac ,

I forgot one more thing to report. Through reading pdf, I found a few typos as follows.

In page 9
<img width="1018" alt="Screen Shot 2021-09-12 at 9 52 15 am" src="https://user-images.githubusercontent.com/44494439/132996028-b5e4710b-b09a-49c7-a99f-c4cec3b9dc00.png">

In page 29
<img width="999" alt="Screen Shot 2021-09-12 at 9 53 31 am" src="https://user-images.githubusercontent.com/44494439/132996071-2e1f0500-7df0-467b-a09a-013a36bccae2.png">

**Comment by jstac** [comment]
Thanks Saya!  Super helpful :-)
