### ISSUE TITLE
[Introduction] link attached to the textbook

### ISSUE THREAD

**Issue by sayaikegawa** [jstac/edtc-code#4]
Hi @jstac ,

I found that the link attached to "Economic Dynamics: Theory and Computation" is broken like below.
<img width="731" alt="Screen Shot 2021-09-10 at 4 25 10 pm" src="https://user-images.githubusercontent.com/44494439/132927375-80dcd198-9c51-47c7-90bd-673fa8575687.png">

<img width="558" alt="Screen Shot 2021-09-10 at 4 29 50 pm" src="https://user-images.githubusercontent.com/44494439/132927587-490dbcb5-9814-48ce-b87a-7b5cd5fec14d.png">

However, "Economic Dynamics: Theory and Computation" and "MIT Press" are not supposed to have any links when I look at md file as follows. So I wonder whether you would like to attach related links to "Economic Dynamics: Theory and Computation" and "MIT Press". If so, could you please tell me which websites you would like to attach?
<img width="556" alt="Screen Shot 2021-09-10 at 4 26 45 pm" src="https://user-images.githubusercontent.com/44494439/132927453-e954ed24-1dfa-4513-8998-10d0683fe808.png">

**Comment by jstac** [comment]
Fixed now, thanks @sayaikegawa

**Comment by sayaikegawa** [comment]
Thank you. I'll close this.
