### ISSUE TITLE
[chapter4] figure 4.11 is mistakenly displayed in pdf.

### ISSUE THREAD

**Issue by sayaikegawa** [jstac/edtc-code#8]
Hi @jstac ,

I need to see other repo first but I just would like to let you know that the figure for figure 4.12 is also used in figure 4.11 in pdf (page 81).

<img width="598" alt="Screen Shot 2021-09-10 at 9 43 50 pm" src="https://user-images.githubusercontent.com/44494439/132936562-b935ba3f-0f19-4be0-8ce3-b7c34111fa19.png">

This figure should be placed as figure 4.11.
<img width="560" alt="Screen Shot 2021-09-10 at 9 47 01 pm" src="https://user-images.githubusercontent.com/44494439/132936572-5752026b-b352-4ca4-a8d8-016c4a8d6561.png">

**Comment by jstac** [comment]
Thank you so much Saya!!!

I really appreciate your help with this.  I have added a special thank you to you in the Preface.

This issue is now fixed.
