### ISSUE TITLE
[Chapter4] order of explanation about figure 4.11

### ISSUE THREAD

**Issue by sayaikegawa** [jstac/edtc-code#9]
Hi @jstac ,

I just want to know whether the order of explanation for each exercise and figure around figure 4.11 is intentionally allocated.

In pdf, exercise 4.24 --> figure 4.11 --> exercise 4.29
In codebook, exercise 4.24 --> exercise 4.29 --> other exercises --> figure 4.11 --> figure 4.12

I think that you allocated the order differently from pdf because figure 4.11 and 4.12 are closely related. But I would like to ask this just in case.

**Comment by jstac** [comment]
Thanks Saya, I will think this over one more time.
